#!/bin/bash

echo "Building binary"

export GO111MODULE=on

echo "Pulling Latest commit"
git remote set-url origin git@github.com:corneredrat/kubectl-which-node.git
git pull -f

echo "Getting latest commitid"
commitid=$(git log --format="%H" -n 1)
echo "Latest comit : $commitid"

echo "Downloading packages"
go mod vendor

echo "Building binary"
go build -mod=vendor -v main.go
if [ $? != 0 ]; then
  echo "Build failed, exiting."
  echo "If problem persists, raise an issue at : https://github.com/corneredrat/kubectl-which-node/issues"
  exit
fi

echo "Installing"
sudo cp main  ./bin/kubectl-which-node
sudo mv main /usr/bin/kubectl-which-node
echo "...Done."
