#!/bin/bash

echo "Refreshing"

export GO111MODULE=on

echo "Pulling Latest commit"
git pull -f
echo "Getting latest commitid"
commitid=$(git log --format="%H" -n 1)
echo "Latest comit : $commitid"
echo "Removing contents in \$GOHOME"
sudo rm -rf $GOHOME

echo "Downloading packages"
go get github.com/corneredrat/kubectl-which-node/cmd@$commitid
go mod download

echo "Correcting packages"
sudo rm -rf ../go/pkg/mod/k8s.io/cli-runtime@v0.18.5
go get k8s.io/cli-runtime@v0.17.0
sudo rm -rf ../go/pkg/mod/github.com/googleapis/gnostic@v0.4.2
go get github.com/googleapis/gnostic@v0.3.0
sudo rm -rf ../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible
go get k8s.io/client-go@v0.17.0
sudo rm -rf  ../go/pkg/mod/k8s.io/apimachinery@v0.18.5
go get k8s.io/apimachinery@v0.17.0
sudo rm -rf  ../go/pkg/mod/k8s.io/api@v0.18.5
go get k8s.io/api@v0.17.0

echo "Building binary"
go build main.go

echo "Installing"
sudo mv main /usr/bin/kubectl-which-node

echo "...Done."

